# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuestionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QuestionWidget(object):
    def setupUi(self, QuestionWidget):
        QuestionWidget.setObjectName("QuestionWidget")
        QuestionWidget.resize(1080, 653)
        self.frame = QtWidgets.QFrame(QuestionWidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 1071, 648))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 410, 1061, 34))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(100, 0, 100, 0)
        self.horizontalLayout_2.setSpacing(105)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.arousalSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.arousalSlider.setFont(font)
        self.arousalSlider.setProperty("value", 50)
        self.arousalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.arousalSlider.setInvertedAppearance(False)
        self.arousalSlider.setInvertedControls(False)
        self.arousalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.arousalSlider.setTickInterval(25)
        self.arousalSlider.setObjectName("arousalSlider")
        self.horizontalLayout_2.addWidget(self.arousalSlider)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 194, 1051, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(100, 0, 100, 0)
        self.horizontalLayout.setSpacing(105)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.valenceSlider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.valenceSlider.setFont(font)
        self.valenceSlider.setMaximum(99)
        self.valenceSlider.setProperty("value", 50)
        self.valenceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.valenceSlider.setInvertedAppearance(False)
        self.valenceSlider.setInvertedControls(False)
        self.valenceSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.valenceSlider.setTickInterval(25)
        self.valenceSlider.setObjectName("valenceSlider")
        self.horizontalLayout.addWidget(self.valenceSlider)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 260, 1061, 151))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.arousalLabel0 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.arousalLabel0.setText("")
        self.arousalLabel0.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Arousal_0.png"))
        self.arousalLabel0.setAlignment(QtCore.Qt.AlignCenter)
        self.arousalLabel0.setObjectName("arousalLabel0")
        self.gridLayout_4.addWidget(self.arousalLabel0, 0, 0, 1, 1)
        self.arousalLabel2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.arousalLabel2.setText("")
        self.arousalLabel2.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Arousal_2.png"))
        self.arousalLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.arousalLabel2.setObjectName("arousalLabel2")
        self.gridLayout_4.addWidget(self.arousalLabel2, 0, 2, 1, 1)
        self.arousalLabel3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.arousalLabel3.setText("")
        self.arousalLabel3.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Arousal_3.png"))
        self.arousalLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.arousalLabel3.setObjectName("arousalLabel3")
        self.gridLayout_4.addWidget(self.arousalLabel3, 0, 3, 1, 1)
        self.arousalLabel1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.arousalLabel1.setText("")
        self.arousalLabel1.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Arousal_1.png"))
        self.arousalLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.arousalLabel1.setObjectName("arousalLabel1")
        self.gridLayout_4.addWidget(self.arousalLabel1, 0, 1, 1, 1)
        self.arousalLabel4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.arousalLabel4.setText("")
        self.arousalLabel4.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Arousal_4.png"))
        self.arousalLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.arousalLabel4.setObjectName("arousalLabel4")
        self.gridLayout_4.addWidget(self.arousalLabel4, 0, 4, 1, 1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 550, 1061, 20))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(70, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(70)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.emotion0 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.emotion0.setText("")
        self.emotion0.setCheckable(True)
        self.emotion0.setChecked(False)
        self.emotion0.setObjectName("emotion0")
        self.horizontalLayout_3.addWidget(self.emotion0)
        self.emotion1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.emotion1.setText("")
        self.emotion1.setObjectName("emotion1")
        self.horizontalLayout_3.addWidget(self.emotion1)
        self.emotion3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.emotion3.setText("")
        self.emotion3.setObjectName("emotion3")
        self.horizontalLayout_3.addWidget(self.emotion3)
        self.emotion4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.emotion4.setText("")
        self.emotion4.setChecked(True)
        self.emotion4.setObjectName("emotion4")
        self.horizontalLayout_3.addWidget(self.emotion4)
        self.emotion2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.emotion2.setText("")
        self.emotion2.setObjectName("emotion2")
        self.horizontalLayout_3.addWidget(self.emotion2)
        self.emotion5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.emotion5.setText("")
        self.emotion5.setObjectName("emotion5")
        self.horizontalLayout_3.addWidget(self.emotion5)
        self.emotion6 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.emotion6.setText("")
        self.emotion6.setObjectName("emotion6")
        self.horizontalLayout_3.addWidget(self.emotion6)
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 1051, 154))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.valenceLabel1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.valenceLabel1.setText("")
        self.valenceLabel1.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Valence_1.png"))
        self.valenceLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.valenceLabel1.setObjectName("valenceLabel1")
        self.gridLayout.addWidget(self.valenceLabel1, 0, 1, 1, 1)
        self.valenceLabel0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.valenceLabel0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.valenceLabel0.setText("")
        self.valenceLabel0.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Valence_0.png"))
        self.valenceLabel0.setAlignment(QtCore.Qt.AlignCenter)
        self.valenceLabel0.setObjectName("valenceLabel0")
        self.gridLayout.addWidget(self.valenceLabel0, 0, 0, 1, 1)
        self.valenceLabel2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.valenceLabel2.setText("")
        self.valenceLabel2.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Valence_2.png"))
        self.valenceLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.valenceLabel2.setObjectName("valenceLabel2")
        self.gridLayout.addWidget(self.valenceLabel2, 0, 2, 1, 1)
        self.valenceLabel4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.valenceLabel4.setText("")
        self.valenceLabel4.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Valence_4.png"))
        self.valenceLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.valenceLabel4.setObjectName("valenceLabel4")
        self.gridLayout.addWidget(self.valenceLabel4, 0, 4, 1, 1)
        self.valenceLabel3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.valenceLabel3.setText("")
        self.valenceLabel3.setPixmap(
            QtGui.QPixmap("../../../data/googledrive/Research-Doctoral/Animations/Valence and Arousal/Valence_3.png"))
        self.valenceLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.valenceLabel3.setObjectName("valenceLabel3")
        self.gridLayout.addWidget(self.valenceLabel3, 0, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(0, 450, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(0, 220, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.nextButton = QtWidgets.QPushButton(self.frame)
        self.nextButton.setGeometry(QtCore.QRect(450, 590, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 490, 1061, 56))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.emotionLabel6_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.emotionLabel6_2.setFont(font)
        self.emotionLabel6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.emotionLabel6_2.setObjectName("emotionLabel6_2")
        self.gridLayout_3.addWidget(self.emotionLabel6_2, 0, 7, 1, 1)
        self.emotionLabel0 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.emotionLabel0.setFont(font)
        self.emotionLabel0.setAlignment(QtCore.Qt.AlignCenter)
        self.emotionLabel0.setObjectName("emotionLabel0")
        self.gridLayout_3.addWidget(self.emotionLabel0, 0, 0, 1, 1)
        self.emotionLabel1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.emotionLabel1.setFont(font)
        self.emotionLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.emotionLabel1.setObjectName("emotionLabel1")
        self.gridLayout_3.addWidget(self.emotionLabel1, 0, 1, 1, 1)
        self.emotionLabel5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.emotionLabel5.setFont(font)
        self.emotionLabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.emotionLabel5.setObjectName("emotionLabel5")
        self.gridLayout_3.addWidget(self.emotionLabel5, 0, 6, 1, 1)
        self.emotionLabel6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.emotionLabel6.setFont(font)
        self.emotionLabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.emotionLabel6.setObjectName("emotionLabel6")
        self.gridLayout_3.addWidget(self.emotionLabel6, 0, 2, 1, 1)
        self.emotionLabel2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.emotionLabel2.setFont(font)
        self.emotionLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.emotionLabel2.setObjectName("emotionLabel2")
        self.gridLayout_3.addWidget(self.emotionLabel2, 0, 4, 1, 1)
        self.emotionLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.emotionLabel.setFont(font)
        self.emotionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.emotionLabel.setObjectName("emotionLabel")
        self.gridLayout_3.addWidget(self.emotionLabel, 0, 3, 1, 1)

        self.retranslateUi(QuestionWidget)
        QtCore.QMetaObject.connectSlotsByName(QuestionWidget)

    def retranslateUi(self, QuestionWidget):
        _translate = QtCore.QCoreApplication.translate
        QuestionWidget.setWindowTitle(_translate("QuestionWidget", "Form"))
        self.label_20.setText(_translate("QuestionWidget", "どういう感情ですか？"))
        self.label_18.setText(_translate("QuestionWidget", "どのぐらい感じますか？"))
        self.nextButton.setText(_translate("QuestionWidget", "次"))
        self.label_17.setText(_translate("QuestionWidget", "何を感じますか？"))
        self.emotionLabel6_2.setText(_translate("QuestionWidget", "驚いた"))
        self.emotionLabel0.setText(_translate("QuestionWidget", "怒ってる"))
        self.emotionLabel1.setText(_translate("QuestionWidget", "気持ち悪い"))
        self.emotionLabel5.setText(_translate("QuestionWidget", "悲しい"))
        self.emotionLabel6.setText(_translate("QuestionWidget", "喜ぶ"))
        self.emotionLabel2.setText(_translate("QuestionWidget", "怖い"))
        self.emotionLabel.setText(_translate("QuestionWidget", "感じてない"))

    def valenceLevel(self):
        valence = self.valenceSlider.value() / 20
        return valence

    def arousalLevel(self):
        arousal = self.arousalSlider.value() / 20
        return arousal

    def emotionLevel(self):
        valences = [self.emotion0, self.emotion1, self.emotion2, self.emotion3, self.emotion4, self.emotion5, self.emotion6]
        for i in range(0, 7):
            if valences[i].isChecked():
                return i

    def setValenceArousal(self, conf):
        self.valenceLabel0.setPixmap(QtGui.QPixmap(conf["valence0"]))
        self.valenceLabel1.setPixmap(QtGui.QPixmap(conf["valence1"]))
        self.valenceLabel2.setPixmap(QtGui.QPixmap(conf["valence2"]))
        self.valenceLabel3.setPixmap(QtGui.QPixmap(conf["valence3"]))
        self.valenceLabel4.setPixmap(QtGui.QPixmap(conf["valence4"]))

        self.arousalLabel0.setPixmap(QtGui.QPixmap(conf["arousal0"]))
        self.arousalLabel1.setPixmap(QtGui.QPixmap(conf["arousal1"]))
        self.arousalLabel2.setPixmap(QtGui.QPixmap(conf["arousal2"]))
        self.arousalLabel3.setPixmap(QtGui.QPixmap(conf["arousal3"]))
        self.arousalLabel4.setPixmap(QtGui.QPixmap(conf["arousal4"]))
